### ISSUE TITLE
[Proposal] Make buffer size configurable

### ISSUE THREAD

**Issue by randallpittman** [caskater4/pyrocopy#3]
Especially for transferring to a network share, it may be advantageous to have a larger buffer size. I got a 33% speed increase transferring a 740 G file over gigabit to a samba share (Win XP VM to CentOS host) by bumping up the buffer size to as much a 4MiB. I propose making a module-level variable in `pyrocopy.py` that is used in `_copyFile()` to set the buffer size in kiB.

**Comment by randallpittman** [comment]
Default can still be 16, ofc. This seems to be a good value for same-disk operations.

**Comment by caskater4** [comment]
PR merged. Thanks!
