### ISSUE TITLE
[Proposal] Use logger named __name__ rather than the root logger.

### ISSUE THREAD

**Issue by randallpittman** [caskater4/pyrocopy#5]
This allows the logger for this module to be managed by itself in the context of a larger application, and is recommended practice in the [docs ](https://docs.python.org/2/howto/logging.html#advanced-logging-tutorial)for [logging](https://docs.python.org/3/howto/logging.html#advanced-logging-tutorial).

**Comment by caskater4** [comment]
PR merged. Thanks!
